#include "moth_inc_craftin"
int StartingConditional()
{
  object oPC = GetPCSpeaker();
  object oItem = GetItemInSlot(INVENTORY_SLOT_RIGHTHAND, oPC);
  object oShield = GetItemInSlot(INVENTORY_SLOT_LEFTHAND, oPC);
  if(MatchShield(oShield)==FALSE)
  {
  return FALSE;
  }
  if(IPGetIsMeleeWeapon(oItem)==FALSE)
  {
  return FALSE;
  }
  if(GetLevelByClass(CLASS_TYPE_FIGHTER,oPC)<25)
  {
  return FALSE;
  }
  if(GetSkillRank(SKILL_CRAFT_WEAPON,oPC,TRUE)<25)
  {
  return FALSE;
  }
  if(!GetHasFeat(FEAT_IMPROVED_KNOCKDOWN,oPC))
  {
  return FALSE;
  }
  if(GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_BASTARDSWORD,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_BATTLEAXE,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_CLUB,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_DAGGER,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_DWAXE,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_HANDAXE,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_KAMA,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_KATANA,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_KUKRI,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_LIGHTFLAIL,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_LIGHTHAMMER,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_LIGHTMACE,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_LONGSWORD,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_MORNINGSTAR,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_RAPIER,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_SCIMITAR,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_SHORTSWORD,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_SICKLE,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_WARHAMMER,oPC)||
     GetHasFeat(FEAT_EPIC_OVERWHELMING_CRITICAL_WHIP,oPC))
     {
     return TRUE;
     }
     else
     {
     return FALSE;
     }
}
